### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by karinakozarova**
Fixed heading

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@karinakozarova I don't _understand_ the difference between the spaces ...
but if this fixes the header I'm happy to merge. 

image

Thanks for taking the time to fix this! 👍

**Comment by newswim** [comment]
I noticed this as well when I was fixing a different readme.

I think it has something to do with the unicode whitespace characters. There are like twenty of them, 🤷‍♂️

**Comment by nelsonic** [comment]
@newswim thanks ... it's lame _lame_ that we use GitHub's Atom to write our Markdown files and they are inserting invalid characters... anyway, thanks again for fixing. 👍

**Comment by newswim** [comment]
I wonder if it's a region thing. It would be kind of funny if this was another case of one group's unconscious bias working its way into code.

miscellany:
- [Spaces in unicode](https://www.cs.tut.fi/~jkorpela/chars/spaces.html)

**Pull request merged**
